### ISSUE TITLE
About reconstruction?

### ISSUE THREAD

**Issue by ShiguangSun** [zchuning/repo#2]
Hi, I have another question. As mentioned in the title of the 4th section: "RePo: Parsimonious Representation Learning without Reconstruction", but in the repo.py, there is a "# Reconstruction loss for probing",  why is that？

**Comment by zchuning** [comment]
This is for visualization purposes (e.g. to create the bottom row of Fig. 9). The gradient does not backpropagate through the rest of the model.

**Comment by ShiguangSun** [comment]
> This is for visualization purposes (e.g. to create the bottom row of Fig. 9). The gradient does not backpropagate through the rest of the model.

Sorry, I don't get it.  The self.model_optimizer in repo.py inherits from dreamer.py. The model_params in self.model_optimizer in dreamer.py contains the parameters of the encoder. The model_loss in repo.py contains obs_loss. Then the encoder should be involved when optimizing obs_loss, did I understand something wrong?

**Comment by zchuning** [comment]
In lines 46-48 of `repo.py,` the beliefs and posterior states are detached, which means their gradients don't propagate through the rest of the model.

**Comment by ShiguangSun** [comment]
Oh，I see. Thanks！
