### ISSUE TITLE
Questions regarding DMC

### ISSUE THREAD

**Issue by pplntech** [zchuning/repo#4]
Hi, thank you for publishing awesome work with the code. This is very helpful.

I have two questions regard DMC experiments.

1. I wonder what X-axis in Figure 5 means. Does it mean 'total environment steps with action repeat of 2 counted' or 'a number of env.step() call'? Based on the implementation, I assume it is the latter but I would like to make sure.
2. Could you make the performances used for creating plots (specifically Figure 5 and Figure 7) available? This would be helpful to compare RePo with other methods.

Again, thank you so much!

**Comment by zchuning** [comment]
Re: 1, yes, it's the number of env.step() calls, without counting action repeat.
Re: 2, could you clarify what you mean by "performances"? If this means model weights, then they should be reproducible by training from scratch, as confirmed in https://github.com/zchuning/repo/issues/3.

**Comment by pplntech** [comment]
Cool! Thanks for your reply.

I meant "performances" by reward numbers throughout the training that are used to make a plot. But, thanks for the suggestion. Let me try to reproduce with the codebase.

Thanks.
